version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15
    container_name: audite_postgres_dev
    environment:
      POSTGRES_DB: audite_dev
      POSTGRES_USER: audite_user
      POSTGRES_PASSWORD: audite_password_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - audite_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audite_user -d audite_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer para gestionar la base de datos (opcional)
  adminer:
    image: adminer
    container_name: audite_adminer_dev
    restart: always
    ports:
      - "8081:8080"
    networks:
      - audite_network
    depends_on:
      - db

  # Redis para cache (opcional, para futuro)
  redis:
    image: redis:7-alpine
    container_name: audite_redis_dev
    ports:
      - "6379:6379"
    networks:
      - audite_network
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  audite_network:
    driver: bridge 