"""Actualizar modelo AgroDiagnostic para independizarlo

Revision ID: 6897f2cd6fa8
Revises: 
Create Date: 2025-04-01 09:50:33.726445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6897f2cd6fa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agro_diagnostic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('industry_type_id')
        batch_op.drop_column('diagnostic_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agro_diagnostic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnostic_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('industry_type_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'agro_industry_type', ['industry_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'energy_diagnostic', ['diagnostic_id'], ['id'])
        batch_op.drop_column('company_name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
